In [5]:
from __future__ import print_function

import sys, os, copy

os.environ['TERM'] = 'linux'
import numpy as np  
import random
random.seed(1)
import time
import pickle

start_time = time.time()

import fastjet as fj

# import analysis_functions as af
# import preprocess_functions as pf
# import tree_cluster_hist as cluster_h


print('Reclustering and making the jet trees ...')
print('==='*20)
#-----------------------------------------

Reclustering and making the jet trees ...


In [11]:
## Directories and inputs 

plots_dir='plots/'
#os.system('mkdir -p '+plots_dir)

images_plots_dir='images/'
#os.system('mkdir -p '+plots_dir+'/'+images_plots_dir)

cardfile="jet_image_trim_pt550-650_card.dat"
sampletype="val"  # train, val,test
dir_subjets= "out_data/" #Input data, typically out_data/
out_dir="../data/inputTrees/top_tag_reference_dataset/"

##Change Rjet and Clustering Algorithm to input variables 
Rjet=".8"
jetdef_tree = "kt"

In [12]:
### Flags

# Turn to true if preprocessing (shift, rotate, etc)
# rot_boost_rot_flip=True
rot_boost_rot_flip=False

In [21]:
print('Loading files for subjets')
print('Subjet array format ([[[pTsubj1],[pTsubj2],...],[[etasubj1],[etasubj2],...],[[phisubj1],[phisubj2],...]])')
print('-----------'*10)

subjetlist = [filename for filename in np.sort(os.listdir(dir_subjets)) if (sampletype in filename and filename.endswith('.pkl'))]
print(subjetlist)
# subjetlist = [filename for filename in np.sort(os.listdir(dir_subjets)) if ('subjets' in filename and eventtype in filename and 'nompi_5' in filename and filename.endswith('.dat'))]

N_analysis=len(subjetlist)
print('Number of subjet files =',N_analysis)
print('Loading subjet files...  \n {}'.format(subjetlist))

images=[]
jetmasslist=[]


## Loop over the data
#jet_mass_difference=[]

#for ifile in range(N_analysis):
for ifile in [1]:
    outputfile=out_dir+'tree_'+subjetlist[ifile].split('.')[0]+'.pkl'
    print(str(outputfile))
#     if(Ntotjets>N_jets):
#         break
     
    file=dir_subjets+subjetlist[ifile]
    with open(file, "rb") as f: jets_file =pickle.load(f) 
   
    #Loop over all the events
    for element in jets_file:
        print(element['leaves'])

Loading files for subjets
Subjet array format ([[[pTsubj1],[pTsubj2],...],[[etasubj1],[etasubj2],...],[[phisubj1],[phisubj2],...]])
--------------------------------------------------------------------------------------------------------------
['val_jets.pkl', 'val_jets_test.pkl']
Number of subjet files = 2
Loading subjet files...  
 ['val_jets.pkl', 'val_jets_test.pkl']
../data/inputTrees/top_tag_reference_dataset/tree_val_jets_test.pkl


TypeError: list indices must be integers or slices, not str

In [9]:


  


    jet_pT=[]
    jet_mass=[]
  
    reclustered_jets=[]

  #Loop over all the events
    for element in jets_file:
        print(element['leaves'])
        event=pf.make_pseudojet(element['leaves'])
#     print('Event const=',event)
#6        label=element[1]
#     print('label=',label)

    # Recluster jet constituents
        out_jet = pf.recluster(event, str(Rjet),str(jetdef_tree)) 
        print(str(Rjet),str(jetdef_tree))
       
        print('length out_jet =',len(out_jet)) 
#     print('Jets [m,pT,eta,phi,pz]=',[[subjet.m(),subjet.perp(),subjet.eta(),subjet.phi_std(),subjet.pz()] for subjet in out_jet])


Loading files for subjets
Subjet array format ([[[pTsubj1],[pTsubj2],...],[[etasubj1],[etasubj2],...],[[phisubj1],[phisubj2],...]])
--------------------------------------------------------------------------------------------------------------
['val_jets.pkl', 'val_jets_test.pkl']
Number of subjet files = 2
Loading subjet files...  
 ['val_jets.pkl', 'val_jets_test.pkl']
../data/inputTrees/top_tag_reference_datasettree_val_jets.pkl
out_data/val_jets.pkl
[[408.25170173 233.69295763 234.25219491 239.10623737]
 [128.71941763  76.0948438   74.47787777  72.31451701]
 [ 52.19524742  30.27149845  31.32922721  28.63854544]]


NameError: name 'pf' is not defined

In [ ]:

#-------------------------------------------------------------------------------------------------------------
#Read cardfile
with open(cardfile) as f:
   commands=f.readlines()

commands = [x.strip().split('#')[0].split() for x in commands] 

ptmin=-9999999.
ptmax=9999999.
maxeta=9999999.
matchdeltaR=9999999.
mergedeltaR=9999999.
N_jets=np.inf
# N_jets=100000
# N_jets=100



for command in commands:
  if len(command)>=2:
    if(command[0]=='TRIMMING'):
       Trimming=int(command[1])
#     if(command[0]=='JETDEF'):
#        jetdef_tree=str(command[1])       
    if(command[0]=='PTMIN'):
       ptmin=float(command[1])
    elif(command[0]=='PTMAX'):
       ptmax=float(command[1])
    elif(command[0]=='ETAMAX'):
       etamax=float(command[1])
    elif(command[0]=='MATCHDELTAR'):
       matchdeltaR=float(command[1])
    elif(command[0]=='MERGEDELTAR'):
       mergedeltaR=float(command[1])
#     elif(command[0]=='RJET'): #Radius of the jet
#        Rjet=float(command[1])
    elif(command[0]=='RTRIM'): #Radius for the subjets used for trimming
       Rtrim=float(command[1])
    elif(command[0]=='MINPTFRACTION'): #Min pT fraction for the subjets that pass the trimming filter
       MinPtFraction=float(command[1])
    elif(command[0]=='PREPROCESS'):
       preprocess_label=command[1]
       print('preprocess_label=',preprocess_label)
    elif(command[0]=='MERGE'):
       jetmergeflag=int(command[1])
    elif(command[0]=='NPOINTS'):
       npoints=int(command[1])
    elif(command[0]=='DRETA'):
       DReta=float(command[1])
    elif(command[0]=='DRPHI'):
       DRphi=float(command[1])   
    elif(command[0]=='NCOLORS'):
       Ncolors=int(command[1])
    elif(command[0]=='KAPPA'):
       kappa=float(command[1])
       
preprocess_cmnd=preprocess_label.split('_')    



# print("ptmin",ptmin)
# print("ptmax",ptmax)
# print("etamax",etamax)
# print("matchdeltaR",matchdeltaR)
# print("mergedeltaR",mergedeltaR)


#counter for current entry
n=-1
if not os.path.exists(out_dir):
  os.makedirs(out_dir)

# 
# #-------------------------------------------------------------------------------------------------------------
# # List to be filled to get histograms
# tot_raw_images=[]
# tot_tracks=[]
# tot_towers=[]
# tot_track_tower=[]
# jet_charge=[]
# jet_abs_charge=[]
# tot_ptq=[]
# tot_abs_ptq=[]
# tot_muons=[]
# jet_mass=[]
# jet_pT=[]
# jet_phi=[]
# jet_eta=[]



#-------------------------------------------------------------------------------------------------------------
#///////////////////////////////////////////////////////////////////
#------------------------------------------------------------------------------------------------------------- 
#------------------------------------------------------------------------------


#     #-----------------------   
#     # If preprocessing (shift, rot, etc)
#     if rot_boost_rot_flip:
    
#         # Keep only the leading jet. Then recluster jets in subjets of R=0.3
#         R_preprocess=0.3
#         subjets = pf.recluster(out_jet[0].constituents(), R_preprocess,'kt') 
#     #     print('---'*20)
#     #     print('Subjets [mass]=',[subjet.m() for subjet in subjets])
#     #     print('Subjets [mass,pT,eta,phi,pz]=',[[subjet.m(),subjet.perp(),subjet.eta(), subjet.phi_std(),subjet.pz()] for subjet in subjets]) 
      
#         #------
#         # Preprocess the jet constituents 
#         preprocessed_const_fj= pf.preprocess_nyu(subjets) 
#     #     print('preprocessed_const_fj [pT,eta,phi,m,pz]=',[[const_fj.perp(),const_fj.eta(),const_fj.phi(),const_fj.m(),const_fj.pz()] for const_fj in preprocessed_const_fj])
        
#     #     #--------------------------------
#     #     # Cross-check: leading subjet should have eta=0 (pz=0), phi=0. 2nd leading one should have eta=0 (pz=0). The 3rd one should have pz>0
# #         preprocessed_subjets = pf.recluster(preprocessed_const_fj, R_preprocess,'kt') 
#     #     print(' Number of subjets=',len(preprocessed_subjets))
# #         print('---'*20)
# #         print('Subjets [mass]=',[subjet.m() for subjet in preprocessed_subjets])
# #         print('Subjet mass difference=',np.asarray([subjet.m() for subjet in preprocessed_subjets])-np.asarray([subjet.m() for subjet in subjets]))
# #         print('Subjets [mass,pT,eta,phi,pz]=',[[subjet.m(),subjet.perp(),subjet.eta(), subjet.phi_std(),subjet.pz()] for subjet in preprocessed_subjets])
    
    
#         # Recluster preprocessed jet constituents 
#         preprocessed_subjets = pf.recluster(preprocessed_const_fj, 0.8,'kt') 
# #         print(' Number of subjets=',len(preprocessed_subjets))
# #         print('Subjets [mass,pT,eta,phi,pz]=',[[subjet.m(),subjet.perp(),subjet.eta(), subjet.phi_std(),subjet.pz()] for subjet in preprocessed_subjets])   
# #         print('Jet mass difference=',np.asarray([subjet.m() for subjet in preprocessed_subjets])-np.asarray([subjet.m() for subjet in out_jet])) 
# #         jet_mass_difference.append(np.asarray([subjet.m() for subjet in preprocessed_subjets])-np.asarray([subjet.m() for subjet in out_jet]))
# #         jet_mass_difference.append(preprocessed_subjets[0].m()-out_jet[0].m())
    
#         out_jet=preprocessed_subjets
# #         print('Preprocessed Subjets [mass,pT,eta,phi,pz]=',[[subjet.m(),subjet.perp(),subjet.eta(), subjet.phi_std(),subjet.pz()] for subjet in out_jet])  


    #-----------------------------------
    # #Create a dictionary with all the jet tree info (topology, constituents features: eta, phi, pT, E, muon label)
    jets_tree = pf.make_tree_list(out_jet)
#     print('jets_tree=',jets_tree)
    
    #Keep only the leading jet
    for tree, content, mass, pt in [jets_tree[0]]:
    
#       print('Content=',content)
      jet_pT.append(pt)
      jet_mass.append(mass)
      jet = pf.make_dictionary(tree,content,mass,pt)
    
#       print('jet dictionary=',jet)
      reclustered_jets.append((jet, label))
#       pickle.dump((jet, label), out_file, protocol=2)
      
      counter+=1

#     print('===='*20)
#     print('===='*20)
    
#     if counter>0:
#       break


#------------------------------------------------------------------------------
# print('Max jet_mass_difference with rot=',np.sort(jet_mass_difference)[-50::])

# print('reclustered_jets=',reclustered_jets)

#If preprocessing
if rot_boost_rot_flip:
  out_filename = str(out_dir)+'tree_'+subjetlist[ifile].split('.')[0]+'_'+str(counter)+'_R_'+str(R_preprocess)+'_rot_boost_rot_flip.pkl'
else:
#   out_filename = str(out_dir)+'tree_'+subjetlist[ifile].split('.')[0]+'_'+str(counter)+'.pkl'
  out_filename = str(out_dir)+'Rjet_'+str(Rjet)+'Clustering_'+str(jetdef_tree)+'tree_'+subjetlist[ifile].split('.')[0]+'.pkl'
print('Saving at '+str(out_filename))



# SAVE OUTPUT FILE
print('out_filename=',out_filename)
with open(out_filename, "wb") as f: pickle.dump(reclustered_jets, f, protocol=2) 
    


print('counter=',counter)  
# sys.exit()

  
  
  
  
    
    
    
    
       
#-------------------------------------------------------------------------------------------------------------
# Make histograms: Input= (out_dir,data,bins,plotname,title,xaxis,yaxis)
hist_dir='plots/histograms/top_tag_reference_dataset/'
if not os.path.exists(hist_dir):
  os.makedirs(hist_dir)


